### ISSUE TITLE
Move GoMock to separate build job

### ISSUE THREAD

**Issue by jasonodoom** [cisagov/skeleton-python-library#135]
# 💡 Summary #

Move GMock to its own build job with the artifacts added to the workflow run like in Python wheels in [cisagov/skeleton-python-library](https://github.com/cisagov/skeleton-python-library). 

## Motivation and context ##

Per the request of @mcdonnnj 

## Implementation notes ##
Move this specific section:

```yaml
          PACKAGE_URL: github.com/golang/mock/mockgen
          PACKAGE_VERSION: ${{ steps.setup-env.outputs.gomock-version }}
        run: go install ${PACKAGE_URL}@${PACKAGE_VERSION}
      - name: Build package
  ```
